# Generated by Django 4.2 on 2026-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
